### ISSUE TITLE
UI error on bulk precommitment action

### ISSUE THREAD

**Issue by cbruguera** [SelfKeyFoundation/crowdsale-tester#17]
![bug screenshot from 2017-12-30 09-47-09](https://user-images.githubusercontent.com/2256202/34450815-b8ea5a3a-ed46-11e7-845c-b4786faec677.png)

Browser: Firefox 57.0.1

**Comment by cbruguera** [comment]
A batch of 7 rows was entered for mass pre-commitment, **only the first one** got submitted.

**Comment by Roadmaptr** [comment]
Hi , ı was trying to find giveaway for key . And suddenly your account open on my phone with your wallet info and etc. Be careful about your security . I just logged out . Take care
